{% set name = "atoml" %}
{% set version = "1.1.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/atoml-{{ version }}.tar.gz
  sha256: cda7b3cee4383e37d88e040d9339e75cd257bb1995054046b61d6746f110146c

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
    - pdm-pep517
  run:
    - python >=3.6

test:
  imports:
    - atoml
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/atoml/
  summary: Yet another style preserving TOML library
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - hadim
